### ISSUE TITLE
Handle external PostgreSQL Database and OpenLDAP

### ISSUE THREAD

**Issue by tomapp** [wso2/docker-apim#53]
Hi,

I would like to know how to link the ApiManager container to an external PostgreSQL Database and link it to an OpenLDAP. Is there a way currently to handle this through this repository ? 

Thanks :)

**Comment by pubudu538** [comment]
In order to point to an external PostgreSQL, you only need to do the following.

1. Create relevant databases in PostgreSQL 
2. Update the connection details in master-datasources.xml
https://github.com/wso2/docker-apim/blob/master/docker-compose/pattern-2/api-manager/carbon/repository/conf/datasources/master-datasources.xml
3. Add the Postgres JDBC driver

All details are included in https://docs.wso2.com/display/AM210/Setting+up+PostgreSQL

For OpenLdap, please refer - https://docs.wso2.com/display/AM210/Configuring+Primary+User+Stores

You need to update the relevant files. If you need to update a new file except in [1], add that file to [1] relative to the carbon home.

[1] - https://github.com/wso2/docker-apim/tree/master/docker-compose/pattern-2/api-manager/carbon

**Comment by tomapp** [comment]
That's works great! :) But now i have a problem with analytics and postgres and Analytics : 

`org.wso2.carbon.databridge.core.exception.EventConversionException: Error when converting loganalyzer:1.0.0 `

I found this solution : https://stackoverflow.com/questions/45055154/wso2-api-manager-2-1-analytics-cannot-be-restarted-when-using-oracle-db/45192366#45192366

But i don't know how to upgrade the RDBMS jar.

Any idea ?

**Comment by pubudu538** [comment]
Are you getting the same error? Can you share the error log?

You can upgrade the RDBMS jar as follows.

1. Download the jar file from http://maven.wso2.org/nexus/content/groups/public/org/wso2/carbon/analytics/org.wso2.carbon.analytics.datasource.rdbms/1.3.6/
2. Remove/backup existing org.wso2.carbon.analytics.datasource.rdbms_1.3.0.jar file from <Analytics_Home>/repository/components/plugins/ location.
3. Add new jar file to <Analytics_Home>/repository/components/plugins/ location.

**Comment by tomapp** [comment]
I follow the instructions but i get this error now : 

`am-analytics_1  | [2017-08-01 09:25:14,093] ERROR {org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceComponent} -  Error in activating analytics data service: Error in creating analytics record store with name 'EVENT_STORE': org.wso2.carbon.analytics.datasource.rdbms.RDBMSAnalyticsRecordStore cannot be found by org.wso2.carbon.analytics.dataservice.core_1.3.0
am-analytics_1  | org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsException: Error in creating analytics record store with name 'EVENT_STORE': org.wso2.carbon.analytics.datasource.rdbms.RDBMSAnalyticsRecordStore cannot be found by org.wso2.carbon.analytics.dataservice.core_1.3.0`

Maybe i need to update an other file ?

**Comment by pubudu538** [comment]
Before going further, could you please share complete log you got in the previous issue?

**Comment by tomapp** [comment]
Done! :)

**Comment by pubudu538** [comment]
It looks like loganalyzer stream definition is not deployed in the analytic node. What is the pattern you are using?

**Comment by tomapp** [comment]
I'm using the pattern-2.

**Comment by DilanUA** [comment]
Thanks for your interest in testing out the product. However, we are closing this issue now since it relates to an implementation before the re-architecturing of the repository which is no longer supported.
